// 取樣樂器庫的資料表：每個樂器有哪些錄音樣本（檔名與音高）。
//
// 這張表是產生的，不是手寫的——來源是公開授權的樣本庫 nbrosowsky/tonejs-instruments
// （樣本 CC-BY 3.0，出處：VSCO 2 Community Edition、University of Iowa MIS、Karoryfer、
// Freesound 的貢獻者，逐項見 credit）。為了不要一次抓一整個樂器（平台鋼琴有 85 個音），
// 每個樂器只留最多 12 個樣本、平均分佈，缺的中間音用播放速率內插（±2 個半音內幾乎聽不出來）。
//
// 'synth' 是這個取樣樂器在合成音色庫裡的代理：樣本還沒抓下來（或離線）時先播它，
// 按鍵不會沒聲音。

/** 樣本庫的共同出處，給 UI 顯示授權用。 */
export const SAMPLE_CREDIT = '樣本：tonejs-instruments（CC-BY 3.0）／VSCO 2 CE、University of Iowa MIS、Karoryfer、Freesound';

/**
 * 每個樂器：中文名、樣本資料夾、來源、代理合成音色，以及 { MIDI 音高: 檔名 }。
 * @type {Record<string, { label: string, credit: string, synth: string, base: string, notes: Record<number, string> }>}
 */
export const SAMPLE_LIBRARY = {
  grand: {
    label: '平台鋼琴',
    credit: 'Salamander Grand Piano V3 — Alexander Holm（CC-BY 3.0）',
    synth: 'real:piano',
    base: 'https://tonejs.github.io/audio/salamander/',
    notes: {
      36: 'C2.mp3',
      39: 'Ds2.mp3',
      42: 'Fs2.mp3',
      45: 'A2.mp3',
      48: 'C3.mp3',
      51: 'Ds3.mp3',
      54: 'Fs3.mp3',
      57: 'A3.mp3',
      60: 'C4.mp3',
      63: 'Ds4.mp3',
      66: 'Fs4.mp3',
      69: 'A4.mp3',
      72: 'C5.mp3',
      75: 'Ds5.mp3',
      78: 'Fs5.mp3',
      81: 'A5.mp3',
      84: 'C6.mp3',
      87: 'Ds6.mp3',
      90: 'Fs6.mp3',
      93: 'A6.mp3',
      96: 'C7.mp3',
    },
  },
  'violin': {
    label: '小提琴',
    credit: 'VSCO 2 CE',
    synth: 'real:violin',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/violin/',
    notes: {
      57: 'A3.mp3',
      64: 'E4.mp3',
      69: 'A4.mp3',
      76: 'E5.mp3',
      81: 'A5.mp3',
      88: 'E6.mp3',
      93: 'A6.mp3',
      96: 'C7.mp3',
    },
  },
  'cello': {
    label: '大提琴',
    credit: 'VSCO 2 CE',
    synth: 'real:cello',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/cello/',
    notes: {
      36: 'C2.mp3',
      40: 'E2.mp3',
      44: 'Gs2.mp3',
      47: 'B2.mp3',
      50: 'D3.mp3',
      53: 'F3.mp3',
      56: 'Gs3.mp3',
      59: 'B3.mp3',
      62: 'D4.mp3',
      65: 'F4.mp3',
      68: 'Gs4.mp3',
      72: 'C5.mp3',
    },
  },
  'contrabass': {
    label: '低音提琴',
    credit: 'VSCO 2 CE',
    synth: 'real:bass',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/contrabass/',
    notes: {
      30: 'Fs1.mp3',
      34: 'As1.mp3',
      38: 'D2.mp3',
      42: 'Fs2.mp3',
      45: 'A2.mp3',
      52: 'E3.mp3',
      59: 'B3.mp3',
    },
  },
  'harp': {
    label: '豎琴',
    credit: 'VSCO 2 CE',
    synth: 'real:harp',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/harp/',
    notes: {
      28: 'E1.mp3',
      35: 'B1.mp3',
      41: 'F2.mp3',
      48: 'C3.mp3',
      55: 'G3.mp3',
      62: 'D4.mp3',
      69: 'A4.mp3',
      76: 'E5.mp3',
      83: 'B5.mp3',
      89: 'F6.mp3',
      95: 'B6.mp3',
      101: 'F7.mp3',
    },
  },
  'guitar-acoustic': {
    label: '木吉他',
    credit: 'University of Iowa',
    synth: 'real:guitar',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/guitar-acoustic/',
    notes: {
      38: 'D2.mp3',
      42: 'Fs2.mp3',
      46: 'As2.mp3',
      50: 'D3.mp3',
      54: 'Fs3.mp3',
      58: 'As3.mp3',
      62: 'D4.mp3',
      66: 'Fs4.mp3',
      70: 'As4.mp3',
      74: 'D5.mp3',
    },
  },
  'guitar-nylon': {
    label: '古典吉他',
    credit: 'Freesound（quartertone）',
    synth: 'real:guitar',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/guitar-nylon/',
    notes: {
      35: 'B1.mp3',
      42: 'Fs2.mp3',
      47: 'B2.mp3',
      52: 'E3.mp3',
      57: 'A3.mp3',
      63: 'Ds4.mp3',
      68: 'Gs4.mp3',
      73: 'Cs5.mp3',
      78: 'Fs5.mp3',
      81: 'A5.mp3',
      82: 'As5.mp3',
    },
  },
  'guitar-electric': {
    label: '電吉他',
    credit: 'Karoryfer',
    synth: 'real:guitar',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/guitar-electric/',
    notes: {
      37: 'Cs2.mp3',
      42: 'Fs2.mp3',
      48: 'C3.mp3',
      54: 'Fs3.mp3',
      60: 'C4.mp3',
      66: 'Fs4.mp3',
      72: 'C5.mp3',
      78: 'Fs5.mp3',
      84: 'C6.mp3',
    },
  },
  'bass-electric': {
    label: '電貝斯',
    credit: 'Karoryfer',
    synth: 'real:bass',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/bass-electric/',
    notes: {
      25: 'Cs1.mp3',
      31: 'G1.mp3',
      37: 'Cs2.mp3',
      43: 'G2.mp3',
      49: 'Cs3.mp3',
      55: 'G3.mp3',
      61: 'Cs4.mp3',
      67: 'G4.mp3',
      70: 'As4.mp3',
    },
  },
  'flute': {
    label: '長笛',
    credit: 'VSCO 2 CE',
    synth: 'real:flute',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/flute/',
    notes: {
      60: 'C4.mp3',
      64: 'E4.mp3',
      69: 'A4.mp3',
      72: 'C5.mp3',
      76: 'E5.mp3',
      81: 'A5.mp3',
      84: 'C6.mp3',
      88: 'E6.mp3',
      93: 'A6.mp3',
      96: 'C7.mp3',
    },
  },
  'clarinet': {
    label: '單簧管',
    credit: 'VSCO 2 CE',
    synth: 'real:clarinet',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/clarinet/',
    notes: {
      50: 'D3.mp3',
      53: 'F3.mp3',
      58: 'As3.mp3',
      62: 'D4.mp3',
      65: 'F4.mp3',
      70: 'As4.mp3',
      74: 'D5.mp3',
      77: 'F5.mp3',
      82: 'As5.mp3',
      86: 'D6.mp3',
      90: 'Fs6.mp3',
    },
  },
  'saxophone': {
    label: '薩克斯風',
    credit: 'Karoryfer',
    synth: 'real:sax',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/saxophone/',
    notes: {
      49: 'Cs3.mp3',
      52: 'E3.mp3',
      55: 'G3.mp3',
      59: 'B3.mp3',
      62: 'D4.mp3',
      65: 'F4.mp3',
      68: 'Gs4.mp3',
      71: 'B4.mp3',
      74: 'D5.mp3',
      77: 'F5.mp3',
      80: 'Gs5.mp3',
      81: 'A5.mp3',
    },
  },
  'trumpet': {
    label: '小號',
    credit: 'VSCO 2 CE',
    synth: 'real:trumpet',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/trumpet/',
    notes: {
      53: 'F3.mp3',
      57: 'A3.mp3',
      60: 'C4.mp3',
      63: 'Ds4.mp3',
      65: 'F4.mp3',
      67: 'G4.mp3',
      70: 'As4.mp3',
      74: 'D5.mp3',
      77: 'F5.mp3',
      81: 'A5.mp3',
      84: 'C6.mp3',
    },
  },
  'trombone': {
    label: '長號',
    credit: 'VSCO 2 CE',
    synth: 'real:brass',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/trombone/',
    notes: {
      34: 'As1.mp3',
      39: 'Ds2.mp3',
      44: 'Gs2.mp3',
      48: 'C3.mp3',
      51: 'Ds3.mp3',
      56: 'Gs3.mp3',
      60: 'C4.mp3',
      62: 'D4.mp3',
      65: 'F4.mp3',
    },
  },
  'french-horn': {
    label: '法國號',
    credit: 'VSCO 2 CE',
    synth: 'real:brass',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/french-horn/',
    notes: {
      33: 'A1.mp3',
      36: 'C2.mp3',
      39: 'Ds2.mp3',
      43: 'G2.mp3',
      50: 'D3.mp3',
      53: 'F3.mp3',
      57: 'A3.mp3',
      60: 'C4.mp3',
      74: 'D5.mp3',
      77: 'F5.mp3',
    },
  },
  'tuba': {
    label: '低音號',
    credit: 'VSCO 2 CE',
    synth: 'real:brass',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/tuba/',
    notes: {
      29: 'F1.mp3',
      34: 'As1.mp3',
      39: 'Ds2.mp3',
      41: 'F2.mp3',
      46: 'As2.mp3',
      50: 'D3.mp3',
      53: 'F3.mp3',
      58: 'As3.mp3',
      62: 'D4.mp3',
    },
  },
  'bassoon': {
    label: '低音管',
    credit: 'VSCO 2 CE',
    synth: 'real:clarinet',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/bassoon/',
    notes: {
      43: 'G2.mp3',
      45: 'A2.mp3',
      48: 'C3.mp3',
      55: 'G3.mp3',
      57: 'A3.mp3',
      60: 'C4.mp3',
      64: 'E4.mp3',
      67: 'G4.mp3',
      69: 'A4.mp3',
      72: 'C5.mp3',
    },
  },
  'organ': {
    label: '管風琴',
    credit: 'VSCO 2 CE',
    synth: 'real:organ',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/organ/',
    notes: {
      24: 'C1.mp3',
      30: 'Fs1.mp3',
      36: 'C2.mp3',
      42: 'Fs2.mp3',
      48: 'C3.mp3',
      54: 'Fs3.mp3',
      60: 'C4.mp3',
      66: 'Fs4.mp3',
      72: 'C5.mp3',
      78: 'Fs5.mp3',
      84: 'C6.mp3',
    },
  },
  'harmonium': {
    label: '簧風琴',
    credit: 'Freesound（donyaquick）',
    synth: 'real:accordion',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/harmonium/',
    notes: {
      36: 'C2.mp3',
      39: 'Ds2.mp3',
      42: 'Fs2.mp3',
      45: 'A2.mp3',
      49: 'Cs3.mp3',
      52: 'E3.mp3',
      55: 'G3.mp3',
      58: 'As3.mp3',
      62: 'D4.mp3',
      65: 'F4.mp3',
      69: 'A4.mp3',
      73: 'Cs5.mp3',
      74: 'D5.mp3',
    },
  },
  'xylophone': {
    label: '木琴',
    credit: 'VSCO 2 CE',
    synth: 'real:marimba',
    base: 'https://nbrosowsky.github.io/tonejs-instruments/samples/xylophone/',
    notes: {
      67: 'G4.mp3',
      72: 'C5.mp3',
      79: 'G5.mp3',
      84: 'C6.mp3',
      91: 'G6.mp3',
      96: 'C7.mp3',
      103: 'G7.mp3',
      108: 'C8.mp3',
    },
  },
};
